apiVersion: v1
kind: PersistentVolume
metadata:
  name: weaviate-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: auto-ebs-sc
