apiVersion: v1
kind: Pod
metadata:
  name: i2v-neural
  labels:
    app: i2v-neural
spec:
  containers:
  - name: i2v-neural
    image: semitechnologies/img2vec-pytorch:resnet50
    env:
    - name: ENABLE_CUDA
      value: "0"
    ports:
    - containerPort: 8080
