apiVersion: v1
kind: Service
metadata:
  name: i2v-neural
spec:
  type: ClusterIP
  selector:
    app: i2v-neural
  ports:
  - protocol: TCP
    name: img2vec-neural
    port: 8080
    targetPort: 8080
