apiVersion: v1
kind: Service
metadata:
  name: weaviate
spec:
  type: NodePort
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30051
