apiVersion: v1
kind: PersistentVolume
metadata:
  name: weaviate-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/weaviate-data"
