apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
data:
  QUERY_DEFAULTS_LIMIT: "25"
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
  AUTHENTICATION_APIKEY_ENABLED: "true"
  PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
  DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
  ENABLE_MODULES: "text2vec-openai,img2vec-neural"
  CLUSTER_HOSTNAME: "node1"
  IMAGE_INFERENCE_API: "http://i2v-neural:8080"
  WEAVIATE_URL: "http://weaviate:8080"
  WEAVIATE_GRPC_PORT: "50051"
  WEAVIATE_HTTP_PORT: "8080"
