apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/configmap-weaviate.yaml
  - config/secret-weaviate.yaml
  - storage/persistent-volume.yaml
  - storage/persistent-volume-claim.yaml
  - services/service-weaviate.yaml
  - services/service-i2v-neural.yaml
  - deployments/deployment-weaviate.yaml
  - deployments/deployment-i2v-neural.yaml
